image: Visual Studio 2019

before_build:
  - cmd: dotnet restore name-sorter.sln  

build_script:
  - cmd: dotnet build name-sorter.sln -c Release  

test_script:
  - cmd: dotnet test name-sorter.Tests/name-sorter.Tests.csproj --no-build --verbosity normal  

artifacts:
  - path: sorted-names-list.txt  
  - path: unsorted-names-list.txt 
